### PR TITLE
Added the creation of NDAttributes that describe how the multi-track …

### PR DESCRIPTION
**Pull request by pheest**
…was configured.

I prefer to add this as a method in ADCore/CCDMultiTrack (invoked from the camera class), since the attribute storage itself is not camera-type specific.

### CODE REVIEW

**Comment by MarkRivers** [comment]
Note that your pull request fails to build on Travis because std::string::to_string does not exist in that system.

**Comment by pheest** [comment]
Oh dear. Sorry about that. I’ve replaced the usage with _itoa.

**Comment by MarkRivers** [comment]
_itoa does not fix the problem. Please see the Travis log.

**Comment by pheest** [comment]
The Microsoft compiler tells me I should use _itoa - and not itoa - because it is posix and ISO C++ compliant…
Should have checked that.

OK, snprintf will work.

**Comment by MarkRivers** [comment]
This merge had 2 problems.

- It uses snprintf.  That function is not supported on older versions of vxWorks, and so the Jenkins build at APS failed.  I replaced it with epicsSnprintf.
- It has Windows line endings.  All other files in areaDetector has Linux line endings.  I changed them to Linux line endings.

**Pull request merged**
