### PR TITLE
The noIOCs branch has removed everything for the simDetector and the iocs directory.

### PR DESCRIPTION
**Pull request by MarkRivers**

### CODE REVIEW

**Comment by MarkRivers** [comment]
Note that some of the pluginTests will no longer work because they depend on simDetector.  Those tests probably need to be moved to the ADExample repository.

**Comment by ulrikpedersen** [comment]
Hi Mark,
I'm just back from holidays today and will take a look at this today and tomorrow (it's a lot of changes to find my way around). 

I'll also have a go at making the unittests work - I think they should at least build and run before we do the actual merge into master.

Cheers,
Ulrik

**Comment by ulrikpedersen** [comment]
I like it! This is now a fairly clean library to build :smile: - this will make it easier to make automatic builds of different configurations.

The travis build is now working - and I've removed the unittest dependency on simDetector (it wasn't really used anyway).

Now I'll move on to play with ADExample and see if the new structure works in our environment.

**Comment by MarkRivers** [comment]
Sounds good.  I'm keen to get this merged because I want to make new releases of the Pilatus and Perkin Elmer detectors, and I want to first release ADCore R2-4 with the iocs removed.


________________________________

**Comment by ulrikpedersen** [comment]
I'm basically happy with how ADCore works in this configuration. As I'm assigned to this PR I will merge now.

**Pull request merged**
