### PR TITLE
Added NDPluginAttrPlot.

### PR DESCRIPTION
**Pull request by blaz-kranjc**
Added plugin from issue #245 .

### CODE REVIEW

**Comment by blaz-kranjc** [comment]
Hi Mark,
sorry about that I forgot that writeInt32 also already takes the lock on the plugin. I would expect that the double lock would just stop my code from ever running which does not happen, so we are not using the typical lock implementation. I'll check the asyn code. Hope this is now better.

**Comment by mp49** [comment]
I think the epicsMutexLock is recursive. So as long as the unlock()’s match the lock()’s it shouldn’t cause a deadlock.

Cheers,
Matt

**Comment by blaz-kranjc** [comment]
Yes I went and check the implementation and epicsMutexLock is recursive. Thanks Matt!

**Comment by blaz-kranjc** [comment]
This test segfault was really hard to reproduce (it does not happen on my workstations). I've created a local travis builder container and this is the backtrace, it happens when I call the NDPluginDriver::processCallbacks:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff70a7550 in epicsMutexLock ()
   from /usr/lib/x86_64-linux-gnu/libCom.so.3.14.12.3
(gdb) bt
#0  0x00007ffff70a7550 in epicsMutexLock ()
   from /usr/lib/x86_64-linux-gnu/libCom.so.3.14.12.3
#1  0x00007ffff7904741 in NDArrayPool::release (this=0x1bc77f0, 
    pArray=0x1bca960) at ../NDArrayPool.cpp:251
#2  0x00007ffff7916fb8 in NDArray::release (this=0x1bca960)
    at ../NDArray.cpp:187
#3  0x00007ffff75af7d5 in NDPluginDriver::processCallbacks (this=0x1bc7730, 
    pArray=0x1bcb2d0) at ../NDPluginDriver.cpp:76
#4  0x00007ffff7623390 in NDPluginAttrPlot::processCallbacks (this=0x1bc7730, 
    pArray=0x1bcb2d0) at ../NDPluginAttrPlot.cpp:126
#5  0x00000000004bb229 in AttrPlotPluginTests::attrplot_reset_pv_write::test_method (this=0x7fffffffcdb0) at ../test_NDPluginAttrPlot.cpp:357
#6  0x00000000004ba13c in AttrPlotPluginTests::attrplot_reset_pv_write_invoker
    () at ../test_NDPluginAttrPlot.cpp:328
#7  0x0000000000417bb2 in boost::unit_test::ut_detail::invoker<boost::unit_test::ut_detail::unused>::invoke<void (*)()> (this=0x7fffffffce2f, 
    f=@0x780a78: 0x4ba0f7 <AttrPlotPluginTests::attrplot_reset_pv_write_invoker()>) at /usr/include/boost/test/utils/callback.hpp:56
#8  0x0000000000417894 in boost::unit_test::ut_detail::callback0_impl_t<boost::unit_test::ut_detail::unused, void (*)()>::invoke (this=0x780a70)
    at /usr/include/boost/test/utils/callback.hpp:89
#9  0x00007ffff6e33121 in ?? ()
   from /usr/lib/libboost_unit_test_framework.so.1.46.1
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff6e175ee in boost::execution_monitor::catch_signals(boost::unit_test::callback0<int> const&) ()
   from /usr/lib/libboost_unit_test_framework.so.1.46.1
#11 0x00007ffff6e17eeb in boost::execution_monitor::execute(boost::unit_test::callback0<int> const&) () from /usr/lib/libboost_unit_test_framework.so.1.46.1
#12 0x00007ffff6e3321b in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::unit_test::test_case const&) ()
   from /usr/lib/libboost_unit_test_framework.so.1.46.1
#13 0x00007ffff6e1e991 in boost::unit_test::framework_impl::visit(boost::unit_test::test_case const&) () from /usr/lib/libboost_unit_test_framework.so.1.46.1
#14 0x00007ffff6e4f093 in boost::unit_test::traverse_test_tree(boost::unit_test::test_suite const&, boost::unit_test::test_tree_visitor&) ()
   from /usr/lib/libboost_unit_test_framework.so.1.46.1
#15 0x00007ffff6e4f093 in boost::unit_test::traverse_test_tree(boost::unit_test::test_suite const&, boost::unit_test::test_tree_visitor&) ()
   from /usr/lib/libboost_unit_test_framework.so.1.46.1
#16 0x00007ffff6e1a0c1 in boost::unit_test::framework::run(unsigned long, bool)
    () from /usr/lib/libboost_unit_test_framework.so.1.46.1
#17 0x00007ffff6e3265f in boost::unit_test::unit_test_main(bool (*)(), int, char**) () from /usr/lib/libboost_unit_test_framework.so.1.46.1
#18 0x000000000040dc0a in main (argc=2, argv=0x7fffffffdd68)
    at /usr/include/boost/test/unit_test.hpp:59
```

**Comment by blaz-kranjc** [comment]
I might be abusing the interface for creating NDArray objects, as it seems that they are not destroyed correctly based on the failing tests on travis worker. I've also noticed that in the tests that NDArrays might not be released on destruction. Based on the logs the NDArraNDArray::reserve is called last on every test.
```
...
NDArray::reserve: WARNING, no owner
NDArray::release: WARNING, no owner
NDArray::reserve: WARNING, no owner
```

I've also just realised that I've messed up the commit history on this PR. I've checked out the PR code to test if the merged version behaves differently from the code on my branch and I've accidentally committed code from there. I would expect the pull request to be applied correctly regardless.

**Comment by MarkRivers** [comment]
You are creating NDArrays with "new NDArray".  You should be using NDArrayPool->create().  That will correctly set the reference count, and also check that you have not allocated more memory than the pool allows.

**Comment by blaz-kranjc** [comment]
Mark, does it make sense then to remove NDArray's constructor from the public interface and make it private?
The default constructor is also used by a few other tests, should I create an issue for that?

**Comment by MarkRivers** [comment]
> Mark, does it make sense then to remove NDArray's constructor from the public interface and make it private?

No, we cannot do that. NDPluginFile for example creates an array of NDArrays when it is in Capture mode using "new NDArray", i.e. it does not allocate them from the pool.  If you use "new" then you must not call release() because the pNDArrayPool member is 0.  The NDArray class checks this, printing the "no owner" message that you saw.

**Comment by GDYendell** [comment]
@MarkRivers do you need any more changes to be made for this to be merged?

**Comment by MarkRivers** [comment]
Sorry for the delay on this. I'll look at it when I return from vacation next week.

**Comment by MarkRivers** [comment]
I just merged this into master, and found that was a big mistake.  Here are the problems:

- It does not compile on Windows VS2010.  Here are the errors:
```
../NDPluginTransform.cpp(520) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginTransform.cpp(521) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(23) : error C2065: 'not' : undeclared identifier
../NDPluginAttrPlot.cpp(23) : error C2146: syntax error : missing ')' before identifier 'stop_'
../NDPluginAttrPlot.cpp(23) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(23) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(104) : error C2146: syntax error : missing ')' before identifier 'and'
../NDPluginAttrPlot.cpp(104) : error C2065: 'and' : undeclared identifier
../NDPluginAttrPlot.cpp(104) : error C2143: syntax error : missing ';' before 'static_cast'
../NDPluginAttrPlot.cpp(104) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(104) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(104) : warning C4552: '<' : operator has no effect; expected operator with side-effect
../NDPluginAttrPlot.cpp(107) : error C2181: illegal else without matching if
../NDPluginAttrPlot.cpp(108) : error C2065: 'NAN' : undeclared identifier
../NDPluginAttrPlot.cpp(116) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(130) : error C2146: syntax error : missing ')' before identifier 'and'
../NDPluginAttrPlot.cpp(130) : error C2065: 'and' : undeclared identifier
../NDPluginAttrPlot.cpp(130) : error C2146: syntax error : missing ';' before identifier 'uid'
../NDPluginAttrPlot.cpp(130) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(130) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(130) : warning C4552: '<=' : operator has no effect; expected operator with side-effect
../NDPluginAttrPlot.cpp(141) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(152) : error C2146: syntax error : missing ')' before identifier 'and'
../NDPluginAttrPlot.cpp(152) : error C2065: 'and' : undeclared identifier
../NDPluginAttrPlot.cpp(152) : error C2143: syntax error : missing ';' before 'static_cast'
../NDPluginAttrPlot.cpp(152) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(152) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(152) : warning C4552: '<' : operator has no effect; expected operator with side-effect
../NDPluginAttrPlot.cpp(159) : error C2146: syntax error : missing ';' before identifier 'and'
../NDPluginAttrPlot.cpp(159) : error C2065: 'and' : undeclared identifier
../NDPluginAttrPlot.cpp(159) : error C2146: syntax error : missing ')' before identifier 'attributes_'
../NDPluginAttrPlot.cpp(159) : warning C4552: '<=' : operator has no effect; expected operator with side-effect
../NDPluginAttrPlot.cpp(160) : error C2065: 'attr' : undeclared identifier
../NDPluginAttrPlot.cpp(160) : error C2065: 'attr' : undeclared identifier
../NDPluginAttrPlot.cpp(160) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(160) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(161) : error C2065: 'attr' : undeclared identifier
../NDPluginAttrPlot.cpp(161) : error C2227: left of '->getName' must point to class/struct/union/generic type
        type is ''unknown-type''
../NDPluginAttrPlot.cpp(162) : error C2065: 'attr' : undeclared identifier
../NDPluginAttrPlot.cpp(162) : error C2227: left of '->getDataType' must point to class/struct/union/generic type
        type is ''unknown-type''
../NDPluginAttrPlot.cpp(165) : error C2146: syntax error : missing ')' before identifier 'or'
../NDPluginAttrPlot.cpp(165) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(165) : error C2146: syntax error : missing ';' before identifier 'type'
../NDPluginAttrPlot.cpp(166) : error C2146: syntax error : missing ';' before identifier 'or'
../NDPluginAttrPlot.cpp(166) : warning C4553: '==' : operator has no effect; did you intend '='?
../NDPluginAttrPlot.cpp(166) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(166) : error C2146: syntax error : missing ';' before identifier 'type'
../NDPluginAttrPlot.cpp(167) : error C2146: syntax error : missing ';' before identifier 'or'
../NDPluginAttrPlot.cpp(167) : warning C4553: '==' : operator has no effect; did you intend '='?
../NDPluginAttrPlot.cpp(167) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(167) : error C2146: syntax error : missing ';' before identifier 'type'
../NDPluginAttrPlot.cpp(168) : error C2146: syntax error : missing ';' before identifier 'or'
../NDPluginAttrPlot.cpp(168) : warning C4553: '==' : operator has no effect; did you intend '='?
../NDPluginAttrPlot.cpp(168) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(168) : error C2146: syntax error : missing ';' before identifier 'type'
../NDPluginAttrPlot.cpp(169) : error C2146: syntax error : missing ';' before identifier 'or'
../NDPluginAttrPlot.cpp(169) : warning C4553: '==' : operator has no effect; did you intend '='?
../NDPluginAttrPlot.cpp(169) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(169) : error C2146: syntax error : missing ';' before identifier 'type'
../NDPluginAttrPlot.cpp(170) : error C2146: syntax error : missing ';' before identifier 'or'
../NDPluginAttrPlot.cpp(170) : warning C4553: '==' : operator has no effect; did you intend '='?
../NDPluginAttrPlot.cpp(170) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(170) : error C2146: syntax error : missing ';' before identifier 'type'
../NDPluginAttrPlot.cpp(171) : error C2146: syntax error : missing ';' before identifier 'or'
../NDPluginAttrPlot.cpp(171) : warning C4553: '==' : operator has no effect; did you intend '='?
../NDPluginAttrPlot.cpp(171) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(171) : error C2146: syntax error : missing ';' before identifier 'type'
../NDPluginAttrPlot.cpp(171) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(172) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(172) : warning C4553: '==' : operator has no effect; did you intend '='?
../NDPluginAttrPlot.cpp(187) : warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(211) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(213) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(215) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(226) : error C2146: syntax error : missing ')' before identifier 'and'
../NDPluginAttrPlot.cpp(226) : error C2065: 'and' : undeclared identifier
../NDPluginAttrPlot.cpp(226) : error C2143: syntax error : missing ';' before 'static_cast'
../NDPluginAttrPlot.cpp(226) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(226) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(226) : warning C4552: '<' : operator has no effect; expected operator with side-effect
../NDPluginAttrPlot.cpp(228) : error C2181: illegal else without matching if
../NDPluginAttrPlot.cpp(231) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(232) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(233) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
../NDPluginAttrPlot.cpp(239) : error C2057: expected constant expression
../NDPluginAttrPlot.cpp(239) : error C2466: cannot allocate an array of constant size 0
../NDPluginAttrPlot.cpp(239) : error C2133: 'new_values' : unknown size
../NDPluginAttrPlot.cpp(240) : error C2065: 'NAN' : undeclared identifier
../NDPluginAttrPlot.cpp(273) : error C2146: syntax error : missing ')' before identifier 'or'
../NDPluginAttrPlot.cpp(273) : error C2065: 'or' : undeclared identifier
../NDPluginAttrPlot.cpp(273) : error C2143: syntax error : missing ';' before 'static_cast'
../NDPluginAttrPlot.cpp(273) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(273) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(273) : warning C4552: '>=' : operator has no effect; expected operator with side-effect
../NDPluginAttrPlot.cpp(276) : error C2146: syntax error : missing ')' before identifier 'and'
../NDPluginAttrPlot.cpp(276) : error C2065: 'and' : undeclared identifier
../NDPluginAttrPlot.cpp(276) : error C2143: syntax error : missing ';' before 'static_cast'
../NDPluginAttrPlot.cpp(276) : error C2059: syntax error : ')'
../NDPluginAttrPlot.cpp(276) : error C2143: syntax error : missing ';' before '{'
../NDPluginAttrPlot.cpp(276) : warning C4552: '>=' : operator has no effect; expected operator with side-effect
H:/epics-devel/base-3.15.5/configure/RULES_BUILD:237: recipe for target 'NDPluginAttrPlot.obj' failed
make[3]: *** [NDPluginAttrPlot.obj] Error 2
make[3]: *** Waiting for unfinished jobs....
H:/epics-devel/base-3.15.5/configure/RULES_ARCHS:58: recipe for target 'install.windows-x64' failed
make[2]: *** [install.windows-x64] Error 2
H:/epics-devel/base-3.15.5/configure/RULES_DIRS:84: recipe for target 'pluginSrc.install' failed
make[1]: *** [pluginSrc.install] Error 2
H:/epics-devel/base-3.15.5/configure/RULES_DIRS:84: recipe for target 'ADApp.install' failed
make: *** [ADApp.install] Error 2
```
- It does not compile on vxWorks.  Here are the errors:
```
../NDPluginAttrPlot.cpp: In member function 'void NDPluginAttrPlot::callback_data()':
../NDPluginAttrPlot.cpp:109: error: 'NAN' was not declared in this scope
../NDPluginAttrPlot.cpp: In member function 'asynStatus NDPluginAttrPlot::push_data(epicsInt32, NDAttributeList&)':
../NDPluginAttrPlot.cpp:241: error: 'NAN' was not declared in this scope
make[2]: *** [NDPluginAttrPlot.o] Error 1
```
- It does not have any documentation

- It does not have any OPI screens

Because I had already done some commits to make it work with ADCore R3-0 I will have to manually undo these changes.

**Comment by MarkRivers** [comment]
I managed to fix the errors building on Windows and vxWorks, so I am keeping this merge and NDPluginAttrPlot will be part of ADCore R3-0.  I have pushed my changes to Github.

However, I would like to request that @blaz-kranjc provide html documentation like all of the other plugins, including screen shots of some OPI (edm, CSS-Boy, etc.).  Please also add an OPI screen in the source code.  I won't hold up R3-0 release for these, but I would like to have them in a future release.  Thanks.

**Comment by ulrikpedersen** [comment]
Thanks Mark. @blaz-kranjc is a contractor (Cosylab) and unfortunately no longer here at Diamond. I'll add the job to add the html, screenshot, etc. to @GDYendell todo list - but it will be a little while before he can get around to it.

Created #272 to remind us.

**Pull request merged**
