### PR TITLE
Allow 1-D images, i.e. if ny=0 set ny=1

### PR DESCRIPTION
**Pull request by MarkRivers**
This is a minor fix that allows the ImageJ plugin to work with 1-D arrays (ny=0).  This is useful because the ImageJ Dynamic Profiler can then be used to plot the 1-D array.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
So this would also work if ny==1 (i.e. a 1D array in a 2D container)?

I've never actually had this plugin installed...

**Comment by MarkRivers** [comment]
Yes, it would have previously worked fine if ny=1.  Which plugin have you not installed?  ImageJ?  It's not actually a plugin, it is just a CA client.  Or do you mean NDPluginStdArrays?

**Comment by ulrikpedersen** [comment]
I mean I've never run this ImageJ-plugin. We do have ImageJ installed centrally (i.e. I'm not able to modify it) but always used the mjpg streaming plugin.

**Comment by ulrikpedersen** [comment]
OK, so I've run up the ImageJ Viewer (for the first time ever!).

It works for 2D array - also when dim Y = 1.

However, it does not display anything when I'm running a true 1D NDArray (using output of ADC simdetector -> ROI -> TimeSeries Plugin -> std array plugin). The log doesn't indicate any error - it's just that no display pops up.

The std array plugin :ArrayData PV has the correct data coming out: 20 points, verified with camonitor.

```
Read properties file: /home/up45/EPICS_AD_Viewer.properties  PVPrefix= 13ADCSIM1:image1:
5/4/16 13:43:22.790: Initializing EPICS
5/4/16 13:43:22.881: Trying to connect to EPICS PVs: 13ADCSIM1:image1:
5/4/16 13:43:22.968: Connected to EPICS PVs OK
5/4/16 13:43:28.602: Image display started
5/4/16 13:43:37.441: Image display stopped
```

**Comment by MarkRivers** [comment]
Are you sure you recompiled the ImageJ Viewer, producing a number of .class files from EPICS_ADView.java?  I observed the same thing you did yesterday before I recompiled.

**Comment by ulrikpedersen** [comment]
Well, I deleted all of the .class files in the dir before re-starting imagej and doing the "plugins->compile and run...".

It did feel like imagej was a bit faster at that step the second time around... How can I ensure that the Viewer is really recompiled?

**Comment by ulrikpedersen** [comment]
I've just tried again: first make sure that all .class files are removed; then tell imagej to compile and run the EPICS areaDetector plugin (browsing to my `ADCore/Viewers/ImageJ/EPICS_areaDetector/EPICS_AD_Viewer.java`)

The std array plugin is connected to the TS1 plugin and the output is 1D array with 20 elements. Camonitor confirms updates are coming through.

imagej-no-display

**Comment by MarkRivers** [comment]
Hmm, it's working for me.  Here are my screen shots of the NDStdArrays plugin, the EPICS_AD_Viewer control screen, and the EPICS_AD_Viewer image display.  Note that NY=0,NZ=0 in NDStdArrays but NY=1,NZ=1 in EPICS_AD_Viewer.
ndstdarrays
![epics_adviewer_control]
(https://cloud.githubusercontent.com/assets/6115534/14286515/e3992b6a-fb14-11e5-809c-acf4236fa1d4.png)
epics_adviewer_display
Is the uniqueID updating in your NDStdArrays plugin?  That needs to be updating or the EPICS_AD_Viewer plugin won't work, because it is monitor callbacks on that PV that trigger the image update.

**Comment by ulrikpedersen** [comment]
> Is the uniqueID updating in your NDStdArrays plugin? That needs to be updating or the EPICS_AD_Viewer plugin won't work, because it is monitor callbacks on that PV that trigger the image update.

Yes it's updating and a camonitor is receiving the updates as well.

**Comment by MarkRivers** [comment]
Can you show the screen shot of your NDStdArrays plugin?
Are you certain that the EPICS_AD_Display.java you are compiling has these lines:
 
           if (nz == 0) nz = 1;  // 2-D images without color
           if (ny == 0) ny = 1;  // 1-D images which are OK, useful with dynamic profiler
             if (getsize == 0) return;  // Not valid dimensions
 
If so, why is it working for me and not for you?

**Comment by ulrikpedersen** [comment]
> Are you certain that the EPICS_AD_Display.java you are compiling has these lines:

I do have the relevant line of code in my java plugin (and I've also pulled down your merge from yesterday). Again I also deleted all the .class files in that dir before starting imagej and compile+run the plugin.

```
(imagej_1d) [up45@pc0009 ADCore]$ grep -n 'ny = 1' Viewers/ImageJ/EPICS_areaDetector/EPICS_AD_Viewer.java
351:            if (ny == 0) ny = 1;  // 1-D images which are OK, useful with dynamic profiler
```

> If so, why is it working for me and not for you?

I have no idea. Could it be a version issue?

Imagej version: 1.49t

Java version:
```
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

> Can you show the screen shot of your NDStdArrays plugin?

Sure. With a 2D NDArray with Y=1 it does work like this:

imagej-2d

But with a 1D NDArray (Y=0) it does not work. The counters on the stdarr plugin are incrementing and a camonitor on the ArrayData PV is updating too.

imagej-1d

**Comment by MarkRivers** [comment]
Here is a screen shot of my setup.  I have tried to reproduce your configuration as closely as possible. It is working fine for me, ImageJ is displaying a 20x1 array.
imagejtest
I am running ImageJ 1.50b.

**Comment by MarkRivers** [comment]
Since this is working for me, and since it is such a minor change I am going to merge with master.  We can continue debugging there.  I am going to add some debugging and push back to master.

**Comment by MarkRivers** [comment]
I am committing a version of EPICS_ADViewer.java that changes the location of one debugging statement.  You can then enable debugging by doing the following 2 things:

Temporarily change line 83 in EPICS_ADViewer.java from this
`isDebugMessages = false;`            
to
`isDebugMessages = true;`            

In ImageJ/Edit/IOption/Misc/ check the box labeled **Debug mode**.

When you start the ImageJ plugin to try to display images you will see repeating log messages like the following:

> Monitor callback 
calling updateImage 
Channel Get: 13ADCSIM1:image1:ArraySize0_RBV 
Channel Get: 13ADCSIM1:image1:ArraySize1_RBV 
Channel Get: 13ADCSIM1:image1:ArraySize2_RBV 
Channel Get: 13ADCSIM1:image1:ColorMode_RBV 
got image, sizes: 20 1 1 
about to get pixels 
ImageCanvas.paint: img[13ADCSIM1:image1: (20x1x1x1x1)]

**Comment by MarkRivers** [comment]
Ulrik please post what you get in that log window.  I particularly want to see the "got image, ..." output.

**Comment by ulrikpedersen** [comment]
I enabled the debugging as you described and couldn't understand why I didn't get any more debug messages in the log... It wasn't until I had the log window open when I ran the compile step that I noticed the real problem:

```
setKeyUp: -1
runPlugIn: ij.plugin.Compiler
actionPerformed: time=1460016028005, java.awt.event.ActionEvent[ACTION_PERFORMED,cmd=Compile and Run...,when=1460016028005,modifiers=] on menuitem0
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Tools/JavaScript.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Jama-1.0.3.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/junit.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/optimization.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/parallelcolt-0.9.2.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/netlib-java.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/arpack-combo.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/jtransforms.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/jplasma.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/csparsej.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/jdom.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/BeanShell.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/Jython.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/caj-1.1.5.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/jca-2.3.2.jar
javac classpath: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/3D/ImageJ_3D_Viewer.jar
javac -source 1.6 -target 1.6 -Xlint:unchecked -deprecation -classpath /dls_sw/apps/ImageJ/x86_64/current/ImageJ/ij.jar:/home/up45/github/ADCore/Viewers/ImageJ/EPICS_areaDetector:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Tools/JavaScript.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Jama-1.0.3.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/junit.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/optimization.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/parallelcolt-0.9.2.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/netlib-java.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/arpack-combo.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/jtransforms.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/jplasma.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/csparsej.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/jdom.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/BeanShell.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/Jython.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/caj-1.1.5.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/jca-2.3.2.jar:/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/3D/ImageJ_3D_Viewer.jar /home/up45/github/ADCore/Viewers/ImageJ/EPICS_areaDetector/EPICS_AD_Viewer.java
setKeyUp: -1
runPlugIn: ij.plugin.ClassChecker
runCompiledPlugin: EPICS_AD_Viewer
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Examples
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Tools
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Tools/JavaScript.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/i12_macros
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Jama-1.0.3.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/MosaicJ
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/cisd-jhdf5-batteries_included_lin_win_mac.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Analyze
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Analyze/Color_Histogram.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Analyze/Cell_Counter.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Color
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/junit.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/optimization.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/TomoJ_2.0.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/parallelcolt-0.9.2.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/netlib-java.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/arpack-combo.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/jtransforms.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/jplasma.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/PlotJ_.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TomoJ/csparsej.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/ANKAphase_2_r.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/unversioned
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Scripts
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/jdom.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/BeanShell.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/jars/Jython.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/caj-1.1.5.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/jca-2.3.2.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/NetCDF_.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/SpotTrackerX2D_.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Graphics
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Input-Output
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Input-Output/Animated_Gif.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Input-Output/CINE_File.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Input-Output/Deltavision_Opener.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Input-Output/QuickTime_Plugins.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Input-Output/LSM_Reader.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Input-Output/nifti_io.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/mosaic_plugins.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Azimuthal_Average.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Stacks
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/TurboReg
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/3D
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/3D/ImageJ_3D_Viewer.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/3D/Volume_Viewer.jar
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/3D/Interactive_3D_Surface_Plot.jar
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Filters
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Test
PluginClassLoader.addDirectory: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/Macros
PluginClassLoader.addJar: /dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/HDF5_Vibez.jar
Read properties file: /home/up45/EPICS_AD_Viewer.properties  PVPrefix= 13ADCSIM1:image1:
GUI.getMaxWindowBounds: java.awt.Rectangle[x=0,y=0,width=1920,height=1080]
GUI.getMaxWindowBounds: java.awt.Rectangle[x=0,y=0,width=1920,height=1080]
ImageWindow.xbase: 910 java.awt.Point[x=910,y=101]
7/4/16 9:0:32.579: Initializing EPICS
err >Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
err >	at ij.gui.ImageWindow.windowActivated(ImageWindow.java:556)
err >	at java.awt.Window.processWindowEvent(Window.java:1857)
err >	at java.awt.Window.processEvent(Window.java:1803)
err >	at java.awt.Component.dispatchEventImpl(Component.java:4501)
err >	at java.awt.Container.dispatchEventImpl(Container.java:2081)
err >	at java.awt.Window.dispatchEventImpl(Window.java:2458)
err >	at java.awt.Component.dispatchEvent(Component.java:4331)
err >	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1848)
err >	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:889)
err >	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:409)
err >	at java.awt.Component.dispatchEventImpl(Component.java:4373)
err >	at java.awt.Container.dispatchEventImpl(Container.java:2081)
err >	at java.awt.Window.dispatchEventImpl(Window.java:2458)
err >	at java.awt.Component.dispatchEvent(Component.java:4331)
err >	at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
err >	at java.awt.SentEvent.dispatch(SentEvent.java:55)
err >	at java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:183)
err >	at java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:210)
err >	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:286)
err >	at java.awt.Component.dispatchEventImpl(Component.java:4373)
err >	at java.awt.Container.dispatchEventImpl(Container.java:2081)
err >	at java.awt.Window.dispatchEventImpl(Window.java:2458)
err >	at java.awt.Component.dispatchEvent(Component.java:4331)
err >	at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
err >	at java.awt.SequencedEvent.dispatch(SequencedEvent.java:101)
err >	at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
err >	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
err >	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
err >	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
err >	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
err >	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
err >	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
7/4/16 9:0:32.662: Trying to connect to EPICS PVs: 13ADCSIM1:image1:
7/4/16 9:0:32.748: Connected to EPICS PVs OK
7/4/16 9:0:51.766: Image display started
imagejlog.txt->imagejlog.txt
```

So it looks like someone (probably our imagej maintainers) have been installing your EPICS_AD_Viewer plugin into the imagej plugin dir `/dls_sw/apps/ImageJ/x86_64/current/ImageJ/plugins/EPICS_areaDetector/`. I have been loading the plugin from my home dir but I guess the one in the plugin dir won and got run instead of mine.

I'll see if I can force the new one to run somehow...

**Comment by ulrikpedersen** [comment]
I downloaded the latest imagej and installed it locally (instead of using our central installation) and now it works :smile: 

imagejworking

**Comment by MarkRivers** [comment]
OK good news!

**Pull request merged**
