### PR TITLE
Optionally include useful modules

### PR DESCRIPTION
**Pull request by kmpeters**
Fixes issue #108

### CODE REVIEW

**Comment by MarkRivers** [comment]
I think perhaps sscan and calc belong in the same category as devIocStats and alive.  calc is only needed for sseq, and sscan is only needed if scanning capability is desired.  commonDriverMakefile could be changed accordingly.

I don't like creating a new "extra.db".  It means that all IOC st.cmd files would need to be edited to include it if I want to use devIocStats, which I do. I think commonPlugins.cmd should be changed to add comment lines saying that the optional SSCAN module is required to use that command.  Users are going to need to edit extra.cmd anyway because they won't have "alive", for example, make it simpler and edit commonPlugins.cmd instead.

**Comment by MarkRivers** [comment]
Your indentation in commonDriverMakefile is not consistent with the rest of the file.  It looks like perhaps you used tab characters?  Please do not use tab characters in any files (except Makefile rules, where they are required).

**Comment by ulrikpedersen** [comment]
I'm all in favour of a "lean" basic build - with a couple of options to enable a more complex build if this is desired. However, when the number of options grow, the test-matrix for the maintainers also grow as we (ideally) need to ensure every conceivable combination of options will work (build and run). We can expand our build matrix of course, but I feel we may need to consider alternatives...

Perhaps this is a topic which is a bit beyond this particular PR (and it's just a crazy idea), but how about moving all IOC related stuff out of ADCore and into a separate repo? Then we can keep ADCore as a lean software library and not littered with various IOC configuration files. That way we only have a single (or maybe two) build configuration of the core libraries - and a separate "ADIOCs" repo with the more complex configurations for building IOCs with a whole host of optional dependencies... This idea sort of follows on with what we started when splitting areaDetector drivers apart.

As mentioned, this is just a crazy thought and is not intended to hold up the work ongoing with this PR... :smiley:

**Comment by kmpeters** [comment]
> Your indentation in commonDriverMakefile is not consistent with the rest of the file. It looks like perhaps you used tab characters?

I corrected the indentation.  The lines were copied from xxx/xxxApp/src/Makefile, which uses tabs for indentation.  I failed to notice the mismatch.

> I don't like creating a new "extra.db". It means that all IOC st.cmd files would need to be edited to include it if I want to use devIocStats, which I do.

I moved the content of extra.cmd to commonPlugins.cmd

> I think commonPlugins.cmd should be changed to add comment lines saying that the optional SSCAN module is required to use that command.

I modified the comments.

**Comment by kmpeters** [comment]
> Perhaps this is a topic which is a bit beyond this particular PR (and it's just a crazy idea), but how about moving all IOC related stuff out of ADCore and into a separate repo? Then we can keep ADCore as a lean software library and not littered with various IOC configuration files. That way we only have a single (or maybe two) build configuration of the core libraries - and a separate "ADIOCs" repo with the more complex configurations for building IOCs with a whole host of optional dependencies... This idea sort of follows on with what we started when splitting areaDetector drivers apart.

I think this is an excellent idea.  It would make it much easier to fork the IOC code and include site-specific modules.

**Comment by MarkRivers** [comment]
> and a separate "ADIOCs" repo with the more complex configurations

I have thought of this. It could just be ADSimDetector, just another detector repository. 

The question then becomes where do we put commonDriverMakefile and commonPlugins.cmd?  In ADSimDetector?  In ADCore?  

Mark

**Comment by ulrikpedersen** [comment]
Great! :smile: I was halfway expecting to be booed out with this suggestion!

> I have thought of this. It could just be ADSimDetector, just another detector repository.

That sounds fine to me. I don't actually mind whether the simDetector driver goes in either ADCore or the new IOC repository. My main concern is just that all the IOC-related configurations live in a separate repo.

> The question then becomes where do we put commonDriverMakefile and commonPlugins.cmd?  In ADSimDetector?  In ADCore?

Well, as the commonDriverMakefile is really only used to building IOCs, I would suggest putting it in the new IOC module as well. The idea is to keep ADCore as lean as possible so that the only interface it publish to other developers are include files, libraries and plugin screens (as the basic plugins are part of ADCore).

**Comment by prjemian** [comment]
+1 for the separate IOC repo

Can this separate IOC repo also simplify the user question I hear: 
"Where are the XML files I need to modify for the HDF5 plugin?"

Pete

**Comment by MarkRivers** [comment]
Your pull request still has extra.cmd being loaded from st.cmd.  That should be removed?

**Comment by MarkRivers** [comment]
I manually made most of these changes.  The only change I did not do was the one to st.cmd.

**Pull request closed without merging**
