### PR TITLE
datasets or source=ndattribute should now save xml attribute tags as att...

### PR DESCRIPTION
**Pull request by aglowacki**
...ributes for the datasets

### CODE REVIEW

**Comment by MarkRivers** [comment]
I can't automatically merge this pull request.  Can you merge the current hdf-bugfix branch into your fork and fix any conflicts, then issue the pull request again?

**Comment by aglowacki** [comment]
Just did a merge with areaDetectors ADCore hdf5-bugfix. It should not have conflicts now.

**Comment by ulrikpedersen** [comment]
Uh, that's from the tip of the hdf5-bugfix branch - so it has Marks mistaken commits in them. We need to discuss this before doing anything else... @aglowacki - can I ring you when you're at work?

**Comment by ulrikpedersen** [comment]
Arthur and I agreed to close this one. Arthur will work on a pull request from the issue-66 branch instead. 

Ref. issue #66

**Pull request closed without merging**
