### PR TITLE
Unittest framework

### PR DESCRIPTION
**Pull request by ulrikpedersen**
The start of a Boost.Test driven unittest framework. Not many tests included so far, but the point is to have the framework so that it can easily be expanded.

This change-set also include a few small configuration files for [travis-ci](https://travis-ci.org/areaDetector/ADCore/builds) and [coveralls](https://coveralls.io/r/areaDetector/ADCore) support. Travis builds and runs tests on every Push and Pull Request event. For Pull Requests the status of the build is then automatically posted in the comments section.

Note: this is not to be merged right now as master is being prepared for a release 2-3.

Thanks to @EdWarrick and @ajgdls for helping out with this.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
Whoops, @ajgdls you've broken the build :smile: 

I've had this problem before and it's because the travis ubuntu installation of hdf5 is a bit old and configured to use the old 1.6 API - the newer 1.8 API is available, but not enabled by default.

See here: https://www.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-Open - you basically want to use H5Dopen2 - but if you want it to look cleaner and not have the "2" at the end of the name, you can set a build flag (i.e. a "compatibility macro") to specify that you're using the 1.8 API. See how here: https://www.hdfgroup.org/HDF5/doc/RM/APICompatMacros.html#GlobalSettings

**Comment by ajgdls** [comment]
Thanks @ulrikpedersen , I've made the relevant change and it builds OK now.

**Comment by ulrikpedersen** [comment]
I just noticed that some CI check failed: it looks like the commit on the branch is good and works - but the Pull Request fails (i.e when merged into master). The error is a segfault in test-case "test_Capture". https://travis-ci.org/areaDetector/ADCore/builds/68294358

This is not urgent as we are not about to merge this PR (we're waiting until after release 2-3) - but obviously need to be fixed *sometime* before we get to that.

**Comment by ulrikpedersen** [comment]
I have just tried to reproduce this crash and annoyingly I cannot (on RHEL6). As a double-check I have restarted the travis job now - just to see if it was a one-off issue with the system... Not likely...

**Comment by ulrikpedersen** [comment]
OK, so I triggered the exact same job to run again (build job no. 16) - and this time it did not segfault... Arrggggg!

**Comment by ajgdls** [comment]
Unintentionally I've noticed that if this branch is checked out and set up to build without the boost libraries defined then the compilation fails in the test directory.  The reason is that some required include statements for HDF5 related helper classes are placed inside the BOOST definition statement.  I'm going to move these include statements outside of the check so that compilation completes even if boost is not defined.

A question, can we set up travis to also compile without boost defined to verify that the compilation works in this case?

**Comment by ulrikpedersen** [comment]
Yes, please do fix that @ajgdls 

> A question, can we set up travis to also compile without boost defined to verify that the compilation works in this case?

Yes, it is possible to create multiple (parallel) builds for different configurations. It is done by specifying multiple environments in the "env:" section of the .travis.yml file (each line is one environment configuration) . I have been considering this for also creating a separate "EPICS_LIBCOM_ONLY=YES" build as well... It is a little tricky and the ci scripts will get more complicated; but I can have a go at it.

**Comment by ulrikpedersen** [comment]
Now that release 2-3 is out, I am quite keen to get this one merged into master.

What do you reckon @MarkRivers is this OK?

@ajgdls: please commit/push any outstanding changes/fixes that you might have locally for this branch...

**Comment by ajgdls** [comment]
Hi I don't have anything outstanding for this branch.

**Comment by MarkRivers** [comment]
I just merged this, and pulled to my local working directory.

When I try to build I get the following error:

make[5]: Entering directory `/home/epics/devel/areaDetector-2-3/ADCore/iocs/simDetectorNoIOC/simDetectorNoIOCApp/src/O.linux-x86_64'
/usr/bin/g++ -o simDetectorNoIOCApp -Wl,-Bstatic -L/home/epics/devel/areaDetector-2-3/ADCore/lib/linux-x86_64 -L/home/epics/devel/asyn-4-26/lib/linux-x86_64 -L/home/epics/devel/autosave-5-6-2/lib/linux-x86_64 -L/home/epics/devel/busy-1-6-1/lib/linux-x86_64 -L/home/epics/devel/calc-3-4-2-1/lib/linux-x86_64 -L/home/epics/devel/devIocStats-3-1-14/lib/linux-x86_64 -L/home/epics/devel/seq-2-2-snapshot-2015-05-21/lib/linux-x86_64 -L/home/epics/devel/sscan-2-10-1/lib/linux-x86_64 -L/usr/local/epics/base-3.14.12.5/lib/linux-x86_64 -L/usr/local64/lib -Wl,-rpath,/home/epics/devel/areaDetector-2-3/ADCore/lib/linux-x86_64 -Wl,-rpath,/home/epics/devel/asyn-4-26/lib/linux-x86_64 -Wl,-rpath,/home/epics/devel/autosave-5-6-2/lib/linux-x86_64 -Wl,-rpath,/home/epics/devel/busy-1-6-1/lib/linux-x86_64 -Wl,-rpath,/home/epics/devel/calc-3-4-2-1/lib/linux-x86_64 -Wl,-rpath,/home/epics/devel/devIocStats-3-1-14/lib/linux-x86_64 -Wl,-rpath,/home/epics/devel/seq-2-2-snapshot-2015-05-21/lib/linux-x86_64 -Wl,-rpath,/home/epics/devel/sscan-2-10-1/lib/linux-x86_64 -Wl,-rpath,/usr/local/epics/base-3.14.12.5/lib/linux-x86_64 -Wl,-rpath,/usr/local64/lib        -m64                simDetectorNoIOC.o   -lsimDetector -lNDPlugin -lADBase -lnetCDF -lNeXus -lcalc -lbusy -lsscan -lautosave -ldevIocStats -lasyn -lseq -lpv -lrecIoc -lsoftDevIoc -lmiscIoc -lrsrvIoc -ldbtoolsIoc -lasIoc -ldbIoc -lregistryIoc -ldbStaticIoc -lca -lCom -lsz -lhdf5 -Wl,-Bdynamic -ltiff -ljpeg -lxml2 -lz -lm -lpthread   -lreadline -lm -lrt -ldl -lgcc
/usr/local64/lib/libhdf5.a(H5Z.o): In function `H5Z_init_interface':
H5Z.c:(.text+0x217): undefined reference to `SZ_encoder_enabled'
/usr/local64/lib/libhdf5.a(H5Zszip.o): In function `H5Z_filter_szip':
H5Zszip.c:(.text+0x11d): undefined reference to `SZ_BufftoBuffDecompress'
H5Zszip.c:(.text+0x1a1): undefined reference to `SZ_BufftoBuffCompress'
collect2: ld returned 1 exit status
make[5]: *** [simDetectorNoIOCApp] Error 1

The only difference I see in pluginSrc is in Makefile:

+# Persuade travis (ubuntu 12.04) to use HDF5 API V2 (1.8 rather than default 1.6)
+USR_CXXFLAGS_Linux += -DH5_NO_DEPRECATED_SYMBOLS -DH5Gopen_vers=2

Is this what is causing the error?  My hdf5 library is version 1.8.7.  These are the hdf5 libraries being used:

lrwxrwxrwx 1 root root       16 Dec 22  2013 libhdf5.so -> libhdf5.so.7.0.1
lrwxrwxrwx 1 root root       16 Dec 22  2013 libhdf5.so.7 -> libhdf5.so.7.0.1
-rwxr-xr-x 1 root root  3045532 Dec 22  2013 libhdf5.so.7.0.1



________________________________

**Comment by ulrikpedersen** [comment]
I don't think that relates to the Makefile change (if that was wrong it would result in a compilation failure...) The error looks like you haven't built the HDF5 library with the SZIP (compression) library(?)

**Comment by MarkRivers** [comment]
I found the problem.  It was the changes you made to commonDriverMakefile and commonLibraryMakefile.  You made the sz library optional, and in so doing you linked it before the hdf5 library.  That is incorrect, it must come after the hdf5 library.

This only occurs when building statically.

I fixed the problem and pushed to github.

________________________________

**Comment by ulrikpedersen** [comment]
Ah sorry about that Mark - and thanks for fixing it. We build dynamically so wouldn't have noticed this issue. I will consider making a build matrix on travis which tests both static and dynamic builds. 

BTW, the reason sz (szip) is made optional is that its license is not as open as you would hope - it restricts the use by commercial users, so some sites might not want to include it in their build.

**Comment by MarkRivers** [comment]
Yes, for Linux it would be good to test both static and dynamic, 32 and 64 bit (4 combinations).

On Windows it is good to test 32/64, static/dynamic, debug/non-debug (8 combinations).

________________________________

**Comment by ulrikpedersen** [comment]
I'm working on extending the travis CI build matrix. However, this is limited to Linux only and this is not enough... I will create a new issue ticket to work on a more complete CI.

> Yes, for Linux it would be good to test both static and dynamic, 32 and 64 bit (4 combinations)

I did try to improve this on travis (which is a 64 bit OS). Unfortunately I found that linux-x86 didn't build on there https://travis-ci.org/ulrikpedersen/ADCore/jobs/73160235

Nor does linux-x86 build on my RHEL6 (64bit) desktop. Again I'll defer further discussion to the ticket that I'm about to create.

**Pull request merged**
