### PR TITLE
Suggestions for NDCircularBuff

### PR DESCRIPTION
**Pull request by VyacheslavIsaev**
Hi Mark,

Here I am again suggesting same fixes. :)

1.  Fixing ND circular buffer so it flushes pre-trigger buffer immediately on software trigger. It is because in my case there might not be a sequential image after the trigger.
I added a PV which allows to regulate when buffer is flushed ($(P)$(R)FlushOnSoftTrg). By default the behavior is the same as before. If the parameter is set to 1=Immediately, pre buffer is flushed immediately on Software trigger arrival.

2. Fixing NDArrayRing. Currently buffer holder is deleted on clear request. That makes reuse of the NDArrayRing impossible if you need to clear NDArrayRing in between.

 3. Small change in TIFF plugin which allows to read TIFFs generated in Photoshop or other editor which doesn't saves explicitly parameters with default value.
    sampleFormat = SAMPLEFORMAT_UINT;

Thank you,
Slava Isaev

Project Leader
Cosylab d.d.

### CODE REVIEW

**Comment by VyacheslavIsaev** [comment]
About re-basing: I haven't succeed. Git says that my bases are the same. Probably re-base had to be done before first commit...

**Comment by VyacheslavIsaev** [comment]
Agree, it looks like the code isn't really branched here.  My thought was that makes code consistent and explicitly indicates that this PV is handled.

Would you like me to remove this if-else?

**Comment by MarkRivers** [comment]
I just tested this new feature and it immediately crashed my IOC.

It is easy to reproduce.
- Run the simDetector
- Open and enable NDPluginCircularBuff
- With FlushOnSoftTrg set to the default ("On new image"), press the Trigger button. This works fine.
- Switch FlushOnSoftTrg to Immediately as shown in the screen shot below.
- Press the Trigger button.  It crashes.
image

This is the gdb traceback when it crashes:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `../../bin/linux-x86_64/simDetectorApp st.cmd.linux'.
Program terminated with signal 11, Segmentation fault.
#0  NDArrayRing::size (this=0x0) at ../NDArrayRing.cpp:43
43        if (wrapped_ == 1){
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libX11-1.6.5-1.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 libxcb-1.12-1.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 readline-6.2-10.el7.x86_64 sssd-client-1.16.0-19.el7_5.8.x86_64
(gdb) bt
#0  NDArrayRing::size (this=0x0) at ../NDArrayRing.cpp:43
#1  0x00000000005e1583 in NDPluginCircularBuff::flushPreBuffer (this=0x34ac570)
    at ../NDPluginCircularBuff.cpp:216
#2  0x00000000005e202d in NDPluginCircularBuff::writeInt32 (this=0x34ac570, pasynUser=0x4037ac8, value=1)
    at ../NDPluginCircularBuff.cpp:281
#3  0x0000000001048712 in writeInt32 (drvPvt=0x34ac570, pasynUser=0x4037ac8, value=1)
    at ../../asyn/asynPortDriver/asynPortDriver.cpp:1689
#4  0x00000000010890d5 in processCallbackOutput (pasynUser=0x4037ac8) at ../devBusyAsyn.c:315
#5  0x000000000103e7f8 in queueRequest (pasynUser=0x4037ac8, priority=<optimized out>, timeout=0)
    at ../../asyn/asynDriver/asynManager.c:1534
#6  0x0000000001088d5d in processBusy (pr=0x3501f08) at ../devBusyAsyn.c:492
#7  0x0000000001088688 in process (prec=0x3501f08) at ../busyRecord.c:242
#8  0x000000000111a028 in dbProcess (precord=precord@entry=0x3501f08) at ../../../src/ioc/db/dbAccess.c:588
#9  0x000000000111bdfe in dbPutField (paddr=0x7efb28038a60, dbrType=dbrType@entry=10, pbuffer=0x7efb4c038b88,
    nRequest=1) at ../../../src/ioc/db/dbAccess.c:1233
#10 0x000000000111dccc in dbChannelPutField (chan=<optimized out>, type=type@entry=10, pbuffer=<optimized out>,
    nRequest=<optimized out>) at ../../../src/ioc/db/dbChannel.c:696
#11 0x000000000115bdee in dbChannel_put (chan=<optimized out>, src_type=<optimized out>,
    psrc=psrc@entry=0x7efb4c038b88, no_elements=<optimized out>) at ../../../src/ioc/db/db_access.c:954
#12 0x0000000001158e74 in write_action (mp=0x7efb9c6e8d90, pPayload=0x7efb4c038b88, client=0x7efb50000f88)
    at ../../../src/ioc/rsrv/camessage.c:799
#13 0x000000000115767d in camessage (client=client@entry=0x7efb50000f88)
    at ../../../src/ioc/rsrv/camessage.c:2538
#14 0x0000000001154530 in camsgtask (pParm=0x7efb50000f88) at ../../../src/ioc/rsrv/camsgtask.c:117
#15 0x00000000011a595c in start_routine (arg=0x7efb4c040f00) at ../../src/osi/os/posix/osdThread.c:403
#16 0x00007efc85149e25 in start_thread () from /lib64/libpthread.so.0
#17 0x00007efc84002bad in clone () from /lib64/libc.so.6

@VyacheslavIsaev please see if you can fix this soon.  I have already merged it, and want to release ADCore R3-4.

Also, I had to spend time adding the new FlushOnSoftTrg PV to the medm screen.  When adding a new feature this is something that should be included in the pull request.

**Comment by VyacheslavIsaev** [comment]
Hi Mark, sorry for that.
I am on travel, wasn't checking emails.

I was focused on testing this feature with the images, so I indeed overlooked the case with empty buffer. 

Thank you, for your support.
Slava

**Pull request merged**
