### PR TITLE
build qsrv service into IOC

### PR DESCRIPTION
**Pull request by prjemian**
see http://epics-pvdata.sourceforge.net/informative/developerGuide/developerGuide.html

qsrv allows clients to get, put and monitor V3 PVs (fields of EPICS DB records) via pvAccess.

### CODE REVIEW

**Comment by MarkRivers** [comment]
What is the goal of having the application built with qsrv?  Is it to be able to have V4 clients access the normal EPICS PVs?  Do you have a client in mind?

**Comment by prjemian** [comment]
That's right.  Clients can use pvget/pvput for both v3 and pva data.  Thanks to @mdavidsaver for this.

**Comment by prjemian** [comment]
The client I have in mind is Python (just learning about p4p) which will monitor and acquire image structures.  Such as from `13SIM1:Pva1:Image`

```
user@host ~/.../caqtdm $ /usr/local/epics/base-7.0.1.1/bin/linux-x86_64/pvlist
GUID 0x30F49E5A00000000272F0626, version 1: tcp@[10.0.2.15:5075]
user@host ~/.../caqtdm $ /usr/local/epics/base-7.0.1.1/bin/linux-x86_64/pvlist 0x30F49E5A00000000272F0626
13SIM1:Pva1:Image
user@host ~/.../caqtdm $ /usr/local/epics/base-7.0.1.1/bin/linux-x86_64/pvget 13SIM1:Pva1:Image
13SIM1:Pva1:Image
structure 
    union value
        (none)


user@host ~/.../caqtdm $ /usr/local/epics/base-7.0.1.1/bin/linux-x86_64/pvinfo 13SIM1:Pva1:Image
CHANNEL  : 13SIM1:Pva1:Image
STATE    : CONNECTED
ADDRESS  : 10.0.2.15:5075
epics:nt/NTNDArray:1.0
    union value
        boolean[] booleanValue
        byte[] byteValue
        short[] shortValue
        int[] intValue
        long[] longValue
        ubyte[] ubyteValue
        ushort[] ushortValue
        uint[] uintValue
        ulong[] ulongValue
        float[] floatValue
        double[] doubleValue
    codec_t codec
        string name
        any parameters
    long compressedSize
    long uncompressedSize
    dimension_t[] dimension
        dimension_t
            int size
            int offset
            int fullSize
            int binning
            boolean reverse
    int uniqueId
    time_t dataTimeStamp
        long secondsPastEpoch
        int nanoseconds
        int userTag
    epics:nt/NTAttribute:1.0[] attribute
        epics:nt/NTAttribute:1.0
            string name
            any value
            string descriptor
            int sourceType
            string source
    string descriptor
    alarm_t alarm
        int severity
        int status
        string message
    time_t timeStamp
        long secondsPastEpoch
        int nanoseconds
        int userTag
    display_t display
        double limitLow
        double limitHigh
        string description
        string format
        string units
```

**Comment by prjemian** [comment]
that `caqtdm` directory is incidental to documenting this...

**Pull request merged**
