### PR TITLE
New scatter/gather capability for plugins

### PR DESCRIPTION
**Pull request by MarkRivers**
Added new NDPluginScatter and NDPluginGather to do scatter/gather operations.  These allow multiple plugins to operate in parallel on different NDArrays, increasing the total number of NDArrays that can be processed per second.  This should be useful for example with NDPluginStats or NDPluginProcess where a single plugin instance is not able to keep up with the detector frame rate.  This addresses issue #256.

The NDPluginGather plugin has the option to sort the incoming plugins by UniqueId which can be convenient for output files.

The NDPluginDriver base class was modified slightly.  This change allows the NDPluginScatter plugin to set a flag when it does a callback with an NDArray indicating that if the NDArray cannot be queued that the NDPluginDriver should return a flag indicating this but not treat this as a dropped array in that plugin.  This allows the NDPluginScatter plugin to try other plugins to see if they have room in their queues before it will finally give up.

There is a detailed example of the use of the scatter/gather functionality in the [NDPluginGather documentation](http://cars.uchicago.edu/software/epics/NDPluginGather.html).

### CODE REVIEW

**Comment by MarkRivers** [comment]
I had neglected to update the [NDPluginGather documentation](http://cars.uchicago.edu/software/epics/NDPluginGather.html) on our Web site after the latest fixes and additions.  @ulrikpedersen and @brunoseivam if you looked earlier please reload.

**Comment by brunoseivam** [comment]
Hi @MarkRivers, could you please also commit the autoconverted screens for Scatter/Gather to opis?

**Comment by MarkRivers** [comment]
I am not set up to do that autoconversion any more.  Tim used to do it, but it is a lot of work.  I wish we could come up with an automated script for all of them, but the CSS-Boy converter can only be run in the CSS GUI as far as I know.

**Comment by brunoseivam** [comment]
OK, I will try it here on my end

**Comment by MarkRivers** [comment]
I am closing this since it has been superseded by #261.

**Pull request closed without merging**
