### PR TITLE
Added new time series plugin

### PR DESCRIPTION
**Pull request by MarkRivers**
New plugin to for time-series data. The plugin accepts input arrays of dimensions [NumSignals] or [NumSignals, NewTimePoints]. The plugin creates NumSignals 1-D arrays of dimension [NumTimPoints], each of which is the time-series for one signal. On each callback the new time points are appended to the existing time series arrays. The plugin can operate in one of two mdes. In Fixed Length mode the time-series arrays are cleared when acquisition starts, and new time points are appended until NumTimePoints points have been received, at which point acquisition stops and further callbacks are ignorred. In Circular Buffer mode on NumTimePoints samples are received then acquisition continues with the new time points replacing the oldest ones in the circular buffer. In this mode the OPI displays always show the latest NumTimePoints samples, with the most recent point on the right. The plugin can also optionally compute 1-D FFTs of the time-series data, and exports the real part, imaginary part, and absolute value of the FFT for each signal.
This plugin is used by R7-0 and later of the quadEM module. It should also be useful for devices like ADCs, transient digitizers, and other devices that produce time-series data on one or more input signals.
There is a new ADCSimDetector test application in areaDetector/ADExample that tests and demonstrates this plugin. This test application simulates a buffered ADC with 8 input waveform signals.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
@MarkRivers: Looking at this today.

@thomascobb: please help me review this and areaDetector/ADExample#4 - it sounds relevant to some of the stuff you're working on(?)

**Comment by ulrikpedersen** [comment]
Whoops, segfault.

I increased the "# Time Points" from 2048 up to 10000 in circular buffer mode and took a few samples - then reduced the "# Time Points" down to 3000 and boom... 


Backtrace (grrrr - unfortunately I've got optimization switched on :angry:) :

```
Program terminated with signal 11, Segmentation fault.
#0  0x0000003107689a8f in memcpy () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64 libgcc-4.4.7-16.el6.x86_64 libjpeg-turbo-1.2.1-3.el6_5.x86_64 libstdc++-4.4.7-16.el6.x86_64 libtiff-3.9.4-10.el6_5.x86_64 libxml2-2.7.6-20.el6_7.1.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 nss-softokn-freebl-3.14.3-23.el6_7.x86_64 readline-6.0-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000003107689a8f in memcpy () from /lib64/libc.so.6
#1  0x00007f0ea71c56e1 in NDPluginTimeSeries::doTimeSeriesCallbacks (this=0x271a260)
    at ../NDPluginTimeSeries.cpp:465
#2  0x00007f0ea71c5b18 in NDPluginTimeSeries::writeInt32 (this=0x271a260, 
    pasynUser=0x326a998, value=1) at ../NDPluginTimeSeries.cpp:383
#3  0x00007f0ea5f56471 in writeInt32 (drvPvt=0x271a260, pasynUser=0x326a998, value=1)
    at ../../asyn/asynPortDriver/asynPortDriver.cpp:1390
#4  0x00007f0ea5f607a3 in processCallbackOutput (pasynUser=0x326a998)
    at ../../asyn/devEpics/devAsynInt32.c:486
#5  0x00007f0ea5f390a8 in queueRequest (pasynUser=0x326a998, priority=asynQueuePriorityLow, 
    timeout=0) at ../../asyn/asynDriver/asynManager.c:1483
#6  0x00007f0ea5f5ec77 in processBo (pr=0x278e490) at ../../asyn/devEpics/devAsynInt32.c:1045
#7  0x00007f0ea5d054c8 in writeValue (prec=0x278e490) at ../boRecord.c:394
#8  process (prec=0x278e490) at ../boRecord.c:242
#9  0x00007f0ea509b2d5 in dbProcess (precord=0x278e490) at ../dbAccess.c:637
#10 0x00007f0ea50a672d in scanList (psl=0x3713270) at ../dbScan.c:688
#11 0x00007f0ea50a7968 in periodicTask (arg=0x3713270) at ../dbScan.c:561
#12 0x00007f0ea47e329d in start_routine (arg=0x38dc2f0)
    at ../../../src/libCom/osi/os/posix/osdThread.c:397
#13 0x0000003107a07aa1 in start_thread () from /lib64/libpthread.so.0
#14 0x00000031076e893d in clone () from /lib64/libc.so.6

(gdb) up
#1  0x00007f0ea71c56e1 in NDPluginTimeSeries::doTimeSeriesCallbacks (this=0x271a260)
    at ../NDPluginTimeSeries.cpp:465
465	      memcpy(dst, src, numCopy*sizeof(double));
(gdb) print dst
$1 = <value optimized out>
(gdb) print src
$2 = <value optimized out>
(gdb) print numCopy
$3 = <value optimized out>

```

For the moment I'll just post the report here, continue my review and possibly come back to this one later :smile:

**Comment by ulrikpedersen** [comment]
OK now a backtrace without optimization and I think the problem is when shrinking the number of points we can get into a state where we accidentally try to copy a negative number of elements...

```
(gdb) 
#0  0x0000003107689a9b in memcpy () from /lib64/libc.so.6
#1  0x00007ff7f9694285 in NDPluginTimeSeries::doTimeSeriesCallbacks (this=0x179d0f0)
    at ../NDPluginTimeSeries.cpp:465
#2  0x00007ff7f9693da9 in NDPluginTimeSeries::writeInt32 (this=0x179d0f0, 
    pasynUser=0x22ee378, value=1) at ../NDPluginTimeSeries.cpp:383
#3  0x00007ff7f83e4471 in writeInt32 (drvPvt=0x179d0f0, pasynUser=0x22ee378, value=1)
    at ../../asyn/asynPortDriver/asynPortDriver.cpp:1390
#4  0x00007ff7f83ee7a3 in processCallbackOutput (pasynUser=0x22ee378)
    at ../../asyn/devEpics/devAsynInt32.c:486
#5  0x00007ff7f83c70a8 in queueRequest (pasynUser=0x22ee378, priority=asynQueuePriorityLow, 
    timeout=0) at ../../asyn/asynDriver/asynManager.c:1483
#6  0x00007ff7f83ecc77 in processBo (pr=0x1811320) at ../../asyn/devEpics/devAsynInt32.c:1045
#7  0x00007ff7f81934c8 in writeValue (prec=0x1811320) at ../boRecord.c:394
#8  process (prec=0x1811320) at ../boRecord.c:242
#9  0x00007ff7f75292d5 in dbProcess (precord=0x1811320) at ../dbAccess.c:637
#10 0x00007ff7f753472d in scanList (psl=0x2796c80) at ../dbScan.c:688
#11 0x00007ff7f7535968 in periodicTask (arg=0x2796c80) at ../dbScan.c:561
#12 0x00007ff7f6c7129d in start_routine (arg=0x295fd00)
    at ../../../src/libCom/osi/os/posix/osdThread.c:397
#13 0x0000003107a07aa1 in start_thread () from /lib64/libpthread.so.0
#14 0x00000031076e893d in clone () from /lib64/libc.so.6
(gdb) up
#1  0x00007ff7f9694285 in NDPluginTimeSeries::doTimeSeriesCallbacks (this=0x179d0f0)
    at ../NDPluginTimeSeries.cpp:465
465	      memcpy(dst, src, numCopy*sizeof(double));
(gdb) print dst
$1 = (double *) 0x7ff7003c53d0
(gdb) print src
$2 = (double *) 0x7ff700405b18
(gdb) print numCopy
$3 = 18446744073709545617
(gdb) print numTimePoints_
$4 = 3000
(gdb) print currentTimePoint_
$5 = 8999
```

**Comment by MarkRivers** [comment]
Thanks for finding it. I had seen the crash once or twice but was unable to reproduce it in many attempts yesterday.


Sent from my iPhone

On Mar 3, 2016, at 5:35 AM, Ulrik Kofoed Pedersen <notifications@github.com<mailto:notifications@github.com>> wrote:


OK now a backtrace without optimization and I think the problem is when shrinking the number of points we can get into a state where we accidentally try to copy a negative number of elements...

(gdb)
#0  0x0000003107689a9b in memcpy () from /lib64/libc.so.6
#1  0x00007ff7f9694285 in NDPluginTimeSeries::doTimeSeriesCallbacks (this=0x179d0f0)
    at ../NDPluginTimeSeries.cpp:465
#2  0x00007ff7f9693da9 in NDPluginTimeSeries::writeInt32 (this=0x179d0f0,
    pasynUser=0x22ee378, value=1) at ../NDPluginTimeSeries.cpp:383
#3  0x00007ff7f83e4471 in writeInt32 (drvPvt=0x179d0f0, pasynUser=0x22ee378, value=1)
    at ../../asyn/asynPortDriver/asynPortDriver.cpp:1390
#4  0x00007ff7f83ee7a3 in processCallbackOutput (pasynUser=0x22ee378)
    at ../../asyn/devEpics/devAsynInt32.c:486
#5  0x00007ff7f83c70a8 in queueRequest (pasynUser=0x22ee378, priority=asynQueuePriorityLow,
    timeout=0) at ../../asyn/asynDriver/asynManager.c:1483
#6  0x00007ff7f83ecc77 in processBo (pr=0x1811320) at ../../asyn/devEpics/devAsynInt32.c:1045
#7  0x00007ff7f81934c8 in writeValue (prec=0x1811320) at ../boRecord.c:394
#8  process (prec=0x1811320) at ../boRecord.c:242
#9  0x00007ff7f75292d5 in dbProcess (precord=0x1811320) at ../dbAccess.c:637
#10 0x00007ff7f753472d in scanList (psl=0x2796c80) at ../dbScan.c:688
#11 0x00007ff7f7535968 in periodicTask (arg=0x2796c80) at ../dbScan.c:561
#12 0x00007ff7f6c7129d in start_routine (arg=0x295fd00)
    at ../../../src/libCom/osi/os/posix/osdThread.c:397
#13 0x0000003107a07aa1 in start_thread () from /lib64/libpthread.so.0
#14 0x00000031076e893d in clone () from /lib64/libc.so.6
(gdb) up
#1  0x00007ff7f9694285 in NDPluginTimeSeries::doTimeSeriesCallbacks (this=0x179d0f0)
    at ../NDPluginTimeSeries.cpp:465
465       memcpy(dst, src, numCopy*sizeof(double));
(gdb) print dst
$1 = (double *) 0x7ff7003c53d0
(gdb) print src
$2 = (double *) 0x7ff700405b18
(gdb) print numCopy
$3 = 18446744073709545617
(gdb) print numTimePoints_
$4 = 3000
(gdb) print currentTimePoint_
$5 = 8999


�

**Comment by ulrikpedersen** [comment]
The code in that section was the hint to reproduce the crash: wait until currentpoint is in the later half of a large array - and then change the number of points down to something small.

I think the trouble here is that the user can change some fundamental settings which relate directly to memory management while the plugin is active. I suggest actively preventing the user from changing a number of parameters while the TSAcuiring is on, namely:

* # Time Points
* Averaging time
* AcquireMode
* Time Link

I think these are fundamentally configuration/setup parameters and it would not be a big limitation (or even inconvenience) to the user to have to stop acquisition before changing these.

Of course we should also add sanity checks to the code just before each memcpy/memset to prevent accidental crashes in the future.

**Comment by MarkRivers** [comment]
Is like to avoid that. I think the locks are sufficient to protect against problems. But I bet I forgot to set currentPoint_ to 0 in allocateArrays? I'm on a plane bound for vacation in Florida so I can't see the code now.

Mark

Sent from my iPhone

On Mar 3, 2016, at 5:52 AM, Ulrik Kofoed Pedersen <notifications@github.com<mailto:notifications@github.com>> wrote:


The code in that section was the hint to reproduce the crash: wait until currentpoint is in the later half of a large array - and then change the number of points down to something small.

I think the trouble here is that the user can change some fundamental settings which relate directly to memory management while the plugin is active. I suggest actively preventing the user from changing a number of parameters while the TSAcuiring is on, namely:

  *   # Time Points
  *   Averaging time
  *   AcquireMode
  *   Time Link

I think these are fundamentally configuration/setup parameters and it would not be a big limitation (or even inconvenience) to the user to have to stop acquisition before changing these.

Of course we should also add sanity checks to the code just before each memcpy/memset to prevent accidental crashes in the future.

�

**Comment by ulrikpedersen** [comment]
> But I bet I forgot to set currentPoint_ to 0 in allocateArrays?

Yes. Setting `currentPoint_ = 0;` in allocateArrays() fixes the crashing issue.

> I'm on a plane bound for vacation in Florida so I can't see the code now.

Enjoy! I'm off to Spain tomorrow :sunglasses:

**Comment by ulrikpedersen** [comment]
Regarding the overall functionality of the plugin: @thomascobb and I discussed this and find that it seems to be a fairly unique functionality with the combination of time-series buffering and FFT calculations. Question: shouldn't the plugin be adapted to be also a producer of NDArrays?

In a somewhat related domain @EdWarrick have been working on NDReframe - which according to Tom: reframes a stream of ADC data into different sized chunks, either continuously or as a response to an event on one of the ADC channels. They use that with the DTACQ ADC.

**Comment by ulrikpedersen** [comment]
In summary what just happened here? :smile: At a glance from the commit log it looks a bit like the FFT functionality was split into a separate plugin? Should I have a go at building/testing this now (well, tomorrow)?

**Comment by MarkRivers** [comment]
As you noticed I have refactored this.  This was based on your comment that the NDTimeSeries plugin was "unique", which I took to mean rather specialized. You also suggested that it should export NDArrays, and I agree.  The new NDTimeSeries plugin only handles the time-series aggregation and averaging.  It puts the time-series in waveform records (type double) and exports as an NDArray (of the input data type).  There is a new NDPluginFFT that is designed to handle 1-D or 2-D FFTs, and do TimeToFrequency or FrequencyToTime.  Currently it only handles Nsignals  of 1-D, and only TimeToFrequency.  I think this is needlessly complex, and I plan to change it today so that it only handles a single signal, either 1-D or truly 2-D.  You are welcome to test the current version, but please don't merge yet.  I have not yet updated the documentation to reflect these changes.  

I have updated the ADExample/ADCSimDetector driver to use the new version.

One thing I did not say previously is the main motivation for writing NDPluginTimeSeries plugin was to replace the drvFastSweep driver from the mca module.  That is what has been used in the past to do this time-series support.  But it was limited to epicsInt32 and made a dependency on mca.  NDPluginFFT is designed to replace the SNL program that did FFTs in the quadEM module.  So quadEM will no longer depend on mca or seq, which is good.

**Comment by ulrikpedersen** [comment]
OK, thanks for the summary, Mark. I think that all sounds very reasonable.

As you're still working on it (and I've got something else on today) I'd prefer to wait with my testing.

> please don't merge yet. 

Sure, I'll wait until it's clear it works for all of us.

**Comment by MarkRivers** [comment]
This is now ready to be merged.  I have completed documentation and don't plan to make any more changes to code.

**Comment by ulrikpedersen** [comment]
OK, I'm checking it. So far it seems to work. I should be able to merge today.

**Comment by ulrikpedersen** [comment]
Works for me :+1: 
Merging.

**Comment by MarkRivers** [comment]
Unlucky timing.  I found the bug in NDPluginTimeSeries and tried to push to github less than 5 seconds after you did the merge!  There were some uninitialized private member variables that were causing the crash on windows-x64-static.  That problem is now fixed.  I will merge my fix into master.

The problems with window-x64-debug remain, but they are definitely unrelated to areaDetector.

**Comment by ulrikpedersen** [comment]
ah that's unfortunate timing :grimacing: 

Well good news that you squashed the bug for windows-x64-static!

**Comment by ulrikpedersen** [comment]
BTW we should open a slack channel or something when we're both working on things like this...

**Comment by tacaswell** [comment]
Side note, appveyor (https://www.appveyor.com/) can be used for CI on windows.

**Comment by ulrikpedersen** [comment]
> Side note, appveyor (https://www.appveyor.com/) can be used for CI on windows

I know. I spend ages trying to get it to build ADCore a few months ago - never made it work and got quite fed up with it. Here is the history (the green lights are only partial builds while hacking at the configuration): https://ci.appveyor.com/project/ulrikpedersen/adcore/history 

I played around with appveyor on my own fork: https://github.com/ulrikpedersen/ADCore/commit/700c2e2b885b6dac5e554f30192ed1a7786932a9

Of course we also do have CI for windows with the help of Jenkins, but it only triggers on changes to the top-level areaDetector repo (not changes to ADCore). And it is also a bit limited because it does not post the status back on the commit or Pull Request. https://jenkins.aps.anl.gov/view/AD2/job/epics-areaDetector/

If anyone feels up for the challenge to get a travis-like CI working for Windows, please speak up ;-)

**Pull request merged**
