### PR TITLE
Create V4 plugin and driver

### PR DESCRIPTION
**Pull request by brunoseivam**
Creates NDPluginV4Server, which exports NDArray as NTNDArray in a EPICSv4 server. Creates simDetectorIOCV4, based on simDetectorIOC, to demonstrate the plugin.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
Hi Bruno, thanks for this contribution - complete with docs and example :+1:  

Are you familiar with the work that @dhickin (Dave Hickin) has done as part of the (NSLS-II driven) EPICS V4 collaboration? It is basically the same functionality in a plugin - plus an ADDriver which acts as a receiver or monitor. Dave has an old action to upload his code to the [ADPvAccess](https://github.com/areaDetector/ADPvAccess) repo - I expect he will do this shortly.

As we now have two competing solutions we will need to evaluate which way to go. Ideally the two of you @brunoseivam and @dhickin should talk and form a collaboration with the aim to provide a  unified solution.

There are a few technical differences - one which effects the areaDetector working group is the choice of repository for this code: external (ADPvAccess) or internal in ADCore (like this PR). We certainly need to answer that first.

I have not been able to discuss this with @MarkRivers today as there seem to be some problem sending emails through the APS mail servers... Feel free to pitch in on this thread, Mark.

**Comment by MarkRivers** [comment]
I was going to say the same thing that Ulrik did.  The ADPvAccess repository is where David Hickin was putting his software.  There is actually nothing there yet, but the repository does exist.

Ø  I have not been able to discuss this with @MarkRivers<https://github.com/MarkRivers> today as there seem to be some problem sending emails through the APS mail servers... Feel free to pitch in on this thread, Mark.
Since I did receive this message on my e-mail from github, I assume that in general APS mail servers from outside are working.  Is this a Diamond to APS problem?

Mark

**Comment by brunoseivam** [comment]
Hi guys,

I saw Dave's presentations and his work is very, very interesting. I am really looking forward to put his code to use. However, as he hadn't put his code up yet, I decided to implement this plugin to familiarize myself with areaDetector and v4 codebases. The end result seemed good for me, so I thought I would contribute it back.

As to where to put it, it seemed natural to me for it to reside together with the other plugins. If ADPvAccess is a better place, I can make the pull request there, but as you noted, there's no directory structure yet.

**Comment by dhickin** [comment]
I've had a quick look at Bruno's code. The obvious things I can see are that the value field is incorrect for floating point and unsigned data and that the dataTimeStamp hasn't been set. Otherwise it looks pretty good.

It  doesn't include the attributes yet though.

I should have ADPvAccess pushed tomorrow. I can't really pull anything from Bruno into ADPvAccess because it's just different code.

I can take another look at Bruno's code tomorrow.

________________________________

**Comment by brunoseivam** [comment]
Hi all,

Just to let you know, there is now also a version outside of ADCore tree:

http://github.com/brunoseivam/ADPva

**Comment by ulrikpedersen** [comment]
We had a discussion and made a decision (last week, apologies for my late reply) to go on and merge this contribution into ADCore. I will have a go at putting this on a "feature" branch where we can prepare it for merging into master so it can become part of the next release.

**Comment by ulrikpedersen** [comment]
I have now pulled this code into a new feature branch on ADCore: "v4-plugin" and I am closing this Pull Request.

Bruno: I've noticed that your commits currently do not reference your github user account. This is probably just because you have not registered your (bnl) email address with your github account...

**Pull request closed without merging**
