### PR TITLE
Swmr integration

### PR DESCRIPTION
**Pull request by MarkRivers**
This pull request should not be merged quite yet, but it provides a way to people to easily see what changes will be merged into master soon.

### CODE REVIEW

**Comment by ajgdls** [comment]
Hi @MarkRivers, I've been running system tests with this branch and I've come up against a problem with the Position plugin that forms part of this pull request.  What I find is that if I enable that plugin it instantly starts using up the queue and then dropping arrays.

I've checked and it looks like the plugin has a problem where it is failing to release arrays correctly.  This problem appears to have been highlighted by the recent updates made to NDPluginDriver.

I've got the fix but I would like to test for a little longer, I can push the change to this branch tomorrow?

**Comment by ajgdls** [comment]
Actually, I don't have a fix and I'm not sure why it isn't working.  The plugin appears to block in the call to 

NDPluginDriver::processCallbacks(pArray);

which takes place right at the start of the

void NDPosPlugin::processCallbacks(NDArray *pArray)

method.  Investigation is continuing...

**Comment by ajgdls** [comment]
OK so now I do know, it is because that plugin was not calling start, and so the non-blocking thread was not starting up and processCallbacks was never actually called.  I know there was discussion about starting threads outside of the constructor but I can't find that discussion to reference here.  I am now back to running tests and hopefully pushing the fix tomorrow.

**Comment by MarkRivers** [comment]
I just made some fixes to get it to pass the unit tests in ADCore/ADApp/pluginTests.  Most of the fixes were to the test_NDFileHDF5AttributeDataset.cpp test, because NDAttrStrings have changed their datatype and dimensions.  I also had to change HDFFileReader.h and HDFFileReader.cpp.  I could not figure out what H5Tget_native_type returns for datasets of type H5T_C_S1, so I look instead at the return value from H5Tget_class to detect if it is a string dataset. Please look at these changes to see if you agree.  
The problems were not confined to the unit tests, the unit tests really proved their worth in uncovering a problem in the HDF5 plugin.  It needed a fix for attribute dataset with extra dimensions, it was still assuming that NDAttrString datasets had the additional 256 dimension.  The unit tests now run with no errors.  
I would like to merge into master soon, so please test.

**Comment by ajgdls** [comment]
Hi, I have just been testing the branch.  I've run the unit tests which passed, and I've run my system level tests which test mostly SWMR file writing and positional placement of data within IOCs, and these also all pass.  I've also manually recorded some string attributes and I can see the difference when viewing these using hdfview.

**Comment by ajgdls** [comment]
Hi @MarkRivers, do you have a planned date for when you would be releasing R2-5?  Do you plan to merge this branch into master before that release?  Cheers, Alan

**Comment by MarkRivers** [comment]
I plan to merge both the swmr_integration and v4_plugin branches into master before R2-5 is released. I want to do this ASAP, but I don't have a definite date.  These are the things that I know need to be done before that can happen.  Please add other items to the list if you are aware of any.

- NDFileHDF5.adl needs to have the widgets for SWMR control that were added to the edm files.
- ADBinaries needs a new version of the HDF5 libraries and header files for the latest version of HDF5 with SWMR support.
- All adl files in ADApp/op/adl need to be converted to (edl, opi, ui) in the autoconvert directories.
- I need to build the latest HDF5 on my Linux hosts so I can test the SWMR support
- RELEASE.md needs to be updated with information on the SWMR and V4 features
- We need to document how to work around the problem with the latest V4 modules not working with areaDetector because of the conflict with boost.

Cheers,
Mark

**Comment by ajgdls** [comment]
Hi Mark, OK thanks for letting me know.  I will work on the new ADBinaries version as high priority.

**Comment by ajgdls** [comment]
Hi @MarkRivers, I've pushed a new branch to ADBinaries called testing-hdf5-1.10.0-patch1.  This has the latest HDF5 libraries committed, and I'm running some tests here building shared IOCs on Windows.  Would you be able to test this ADBinaries branch also, especially with static builds if you are able to?

Thanks, Alan

**Comment by MarkRivers** [comment]
Thanks for doing that.  I should be able to test it next week, both static and dynamic, 32 and 64-bit.

**Comment by MarkRivers** [comment]
Hi @ajgdls , I have now tested building on win32-x86, win32-x86-static, windows-x64, and windows-x64-static.  The build for ADCore and all detectors was successful.  

The following warnings are not new in this branch, they also occur in R2-4.  However, it would be nice to eliminate them if possible.

    libszip.lib(sz_api.obj) : warning LNK4049: locally defined symbol malloc imported
    libszip.lib(rice.obj) : warning LNK4049: locally defined symbol malloc imported
    libzlib.lib(zutil.obj) : warning LNK4049: locally defined symbol malloc imported
    libszip.lib(sz_api.obj) : warning LNK4049: locally defined symbol free imported
    libszip.lib(rice.obj) : warning LNK4049: locally defined symbol free imported
    libzlib.lib(zutil.obj) : warning LNK4049: locally defined symbol free imported
    NDPlugin.lib(NDFileHDF5LayoutXML.obj) : warning LNK4049: locally defined symbol xmlFree imported
    "Installing created file ../../../bin/windows-x64-static/simDetectorApp.exe"
    make[1]: Leaving directory 'J:/epics/devel/areaDetector-2-5/ADExample/iocs/simDetectorIOC/simDetectorApp/src/O.windows-x64-static'

**Comment by ajgdls** [comment]
Thanks @MarkRivers I will take a look to see if I can eliminate those warnings.

**Pull request merged**
