### PR TITLE
Changed EnableCallbacks state names from Disable to Disabled, Enable …

### PR DESCRIPTION
**Pull request by bhill-slac**
Makes the GUI less confusing for users by making the state names clearly show the current state instead of potentially an action.

### CODE REVIEW

**Comment by brunoseivam** [comment]
This potentially breaks clients that do

    caput $(P)EnableCallbacks Enable

**Comment by MarkRivers** [comment]
These are all of the occurrences of the string "Enable" in all template files in ADCore.  Note that it is Enable, not Enabled.  Why change it one case?
```
corvette:ADCore/ADApp/Db>grep -U5 Enable *.template
NDArrayBase.template-    field(PINI, "YES")
NDArrayBase.template-    field(DTYP, "asynInt32")
NDArrayBase.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ARRAY_CALLBACKS")
NDArrayBase.template-    field(ZNAM, "Disable")
NDArrayBase.template-    field(ZSV,  "NO_ALARM")
NDArrayBase.template:    field(ONAM, "Enable")
NDArrayBase.template-    field(OSV,  "MINOR")
NDArrayBase.template-    field(VAL, "1")
NDArrayBase.template-    info(autosaveFields, "VAL")
NDArrayBase.template-}
NDArrayBase.template-
--
NDArrayBase.template-{
NDArrayBase.template-    field(DTYP, "asynInt32")
NDArrayBase.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ARRAY_CALLBACKS")
NDArrayBase.template-    field(ZNAM, "Disable")
NDArrayBase.template-    field(ZSV,  "NO_ALARM")
NDArrayBase.template:    field(ONAM, "Enable")
NDArrayBase.template-    field(OSV,  "MINOR")
NDArrayBase.template-    field(SCAN, "I/O Intr")
NDArrayBase.template-}
NDArrayBase.template-
NDArrayBase.template-###################################################################
--
NDFFT.template-{
NDFFT.template-   field(PINI, "YES")
NDFFT.template-   field(DTYP, "asynInt32")
NDFFT.template-   field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))FFT_SUPPRESS_DC")
NDFFT.template-   field(ZNAM, "Disable")
NDFFT.template:   field(ONAM, "Enable")
NDFFT.template-   info(autosaveFields, "VAL")
NDFFT.template-}
NDFFT.template-
NDFFT.template-record(bi, "$(P)$(R)FFTSuppressDC_RBV")
NDFFT.template-{
NDFFT.template-   field(DTYP, "asynInt32")
NDFFT.template-   field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))FFT_SUPPRESS_DC")
NDFFT.template-   field(ZNAM, "Disable")
NDFFT.template:   field(ONAM, "Enable")
NDFFT.template-   field(SCAN, "I/O Intr")
NDFFT.template-}
NDFFT.template-
NDFFT.template-record(longout, "$(P)$(R)FFTNumAverage")
NDFFT.template-{
--
NDPluginBase.template-
NDPluginBase.template-###################################################################
NDPluginBase.template-#  These records control whether callbacks are enabled and        #
NDPluginBase.template-#  minimum time between callbacks                                 #
NDPluginBase.template-###################################################################
NDPluginBase.template:record(bo, "$(P)$(R)EnableCallbacks")
NDPluginBase.template-{
NDPluginBase.template-    field(PINI, "YES")
NDPluginBase.template-    field(DTYP, "asynInt32")
NDPluginBase.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_CALLBACKS")
NDPluginBase.template-    field(ZNAM, "Disable")
NDPluginBase.template:    field(ONAM, "Enable")
NDPluginBase.template-    field(VAL,  "$(ENABLED=0)")
NDPluginBase.template-    info(autosaveFields, "VAL")
NDPluginBase.template-}
NDPluginBase.template-
NDPluginBase.template:record(bi, "$(P)$(R)EnableCallbacks_RBV")
NDPluginBase.template-{
NDPluginBase.template-    field(DTYP, "asynInt32")
NDPluginBase.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_CALLBACKS")
NDPluginBase.template-    field(ZNAM, "Disable")
NDPluginBase.template:    field(ONAM, "Enable")
NDPluginBase.template-    field(ZSV,  "NO_ALARM")
NDPluginBase.template-    field(OSV,  "MINOR")
NDPluginBase.template-    field(SCAN, "I/O Intr")
NDPluginBase.template-}
NDPluginBase.template-
--
NDProcess.template-    field(ZNAM, "No")
NDProcess.template-    field(ONAM, "Yes")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bo, "$(P)$(R)EnableBackground")
NDProcess.template-{
NDProcess.template-    field(PINI, "YES")
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_BACKGROUND")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    info(autosaveFields, "VAL")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bi, "$(P)$(R)EnableBackground_RBV")
NDProcess.template-{
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_BACKGROUND")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    field(ZSV,  "NO_ALARM")
NDProcess.template-    field(OSV,  "MINOR")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
--
NDProcess.template-    field(ZNAM, "No")
NDProcess.template-    field(ONAM, "Yes")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bo, "$(P)$(R)EnableFlatField")
NDProcess.template-{
NDProcess.template-    field(PINI, "YES")
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_FLAT_FIELD")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    info(autosaveFields, "VAL")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bi, "$(P)$(R)EnableFlatField_RBV")
NDProcess.template-{
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_FLAT_FIELD")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    field(ZSV,  "NO_ALARM")
NDProcess.template-    field(OSV,  "MINOR")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
--
NDProcess.template-}
NDProcess.template-
NDProcess.template-###################################################################
NDProcess.template-# These records control the offset and scale                      #
NDProcess.template-###################################################################
NDProcess.template:record(bo, "$(P)$(R)EnableOffsetScale")
NDProcess.template-{
NDProcess.template-    field(PINI, "YES")
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_OFFSET_SCALE")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    info(autosaveFields, "VAL")
NDProcess.template-}
NDProcess.template-
NDProcess.template-# Oneshot record for calculating scale and offset
NDProcess.template-record(busy, "$(P)$(R)AutoOffsetScale")
--
NDProcess.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))AUTO_OFFSET_SCALE")
NDProcess.template-    field(ZNAM, "Done")
NDProcess.template-    field(ONAM, "Calculating")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bi, "$(P)$(R)EnableOffsetScale_RBV")
NDProcess.template-{
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_OFFSET_SCALE")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    field(ZSV,  "NO_ALARM")
NDProcess.template-    field(OSV,  "MINOR")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
--
NDProcess.template-}
NDProcess.template-
NDProcess.template-###################################################################
NDProcess.template-# These records control the high and low clipping                 #
NDProcess.template-###################################################################
NDProcess.template:record(bo, "$(P)$(R)EnableLowClip")
NDProcess.template-{
NDProcess.template-    field(PINI, "YES")
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_LOW_CLIP")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    info(autosaveFields, "VAL")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bi, "$(P)$(R)EnableLowClip_RBV")
NDProcess.template-{
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_LOW_CLIP")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    field(ZSV,  "NO_ALARM")
NDProcess.template-    field(OSV,  "MINOR")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
--
NDProcess.template-    field(DTYP, "asynFloat64")
NDProcess.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))LOW_CLIP")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bo, "$(P)$(R)EnableHighClip")
NDProcess.template-{
NDProcess.template-    field(PINI, "YES")
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_HIGH_CLIP")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    info(autosaveFields, "VAL")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bi, "$(P)$(R)EnableHighClip_RBV")
NDProcess.template-{
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_HIGH_CLIP")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    field(ZSV,  "NO_ALARM")
NDProcess.template-    field(OSV,  "MINOR")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
--
NDProcess.template-}
NDProcess.template-
NDProcess.template-###################################################################
NDProcess.template-# These records control frame filtering                           #
NDProcess.template-###################################################################
NDProcess.template:record(bo, "$(P)$(R)EnableFilter")
NDProcess.template-{
NDProcess.template-    field(PINI, "YES")
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_FILTER")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    info(autosaveFields, "VAL")
NDProcess.template-}
NDProcess.template-
NDProcess.template:record(bi, "$(P)$(R)EnableFilter_RBV")
NDProcess.template-{
NDProcess.template-    field(DTYP, "asynInt32")
NDProcess.template-    field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_FILTER")
NDProcess.template-    field(ZNAM, "Disable")
NDProcess.template:    field(ONAM, "Enable")
NDProcess.template-    field(ZSV,  "NO_ALARM")
NDProcess.template-    field(OSV,  "MINOR")
NDProcess.template-    field(SCAN, "I/O Intr")
NDProcess.template-}
NDProcess.template-
--
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ARRAY_SIZE_Z")
NDROI.template-   field(SCAN, "I/O Intr")
NDROI.template-}
NDROI.template-
NDROI.template:record(bo, "$(P)$(R)EnableX")
NDROI.template-{
NDROI.template-   field(PINI, "YES")
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))DIM0_ENABLE")
NDROI.template-   field(VAL,  "1")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   info(autosaveFields, "VAL")
NDROI.template-}
NDROI.template-
NDROI.template:record(bi, "$(P)$(R)EnableX_RBV")
NDROI.template-{
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))DIM0_ENABLE")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   field(ZSV,  "NO_ALARM")
NDROI.template-   field(OSV,  "MINOR")
NDROI.template-   field(SCAN, "I/O Intr")
NDROI.template-}
NDROI.template-
NDROI.template:record(bo, "$(P)$(R)EnableY")
NDROI.template-{
NDROI.template-   field(PINI, "YES")
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))DIM1_ENABLE")
NDROI.template-   field(VAL,  "1")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   info(autosaveFields, "VAL")
NDROI.template-}
NDROI.template-
NDROI.template:record(bi, "$(P)$(R)EnableY_RBV")
NDROI.template-{
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))DIM1_ENABLE")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   field(ZSV,  "NO_ALARM")
NDROI.template-   field(OSV,  "MINOR")
NDROI.template-   field(SCAN, "I/O Intr")
NDROI.template-}
NDROI.template-
NDROI.template:record(bo, "$(P)$(R)EnableZ")
NDROI.template-{
NDROI.template-   field(PINI, "YES")
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))DIM2_ENABLE")
NDROI.template-   field(VAL,  "1")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   info(autosaveFields, "VAL")
NDROI.template-}
NDROI.template-
NDROI.template:record(bi, "$(P)$(R)EnableZ_RBV")
NDROI.template-{
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))DIM2_ENABLE")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   field(ZSV,  "NO_ALARM")
NDROI.template-   field(OSV,  "MINOR")
NDROI.template-   field(SCAN, "I/O Intr")
NDROI.template-}
NDROI.template-
--
NDROI.template-###################################################################
NDROI.template-#  These records control the scaling of the data.  Useful when    #
NDROI.template-#  binning or converting data types                               #
NDROI.template-###################################################################
NDROI.template-
NDROI.template:record(bo, "$(P)$(R)EnableScale")
NDROI.template-{
NDROI.template-   field(PINI, "YES")
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_SCALE")
NDROI.template-   field(VAL,  "0")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   info(autosaveFields, "VAL")
NDROI.template-}
NDROI.template-
NDROI.template:record(bi, "$(P)$(R)EnableScale_RBV")
NDROI.template-{
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))ENABLE_SCALE")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   field(ZSV,  "NO_ALARM")
NDROI.template-   field(OSV,  "MINOR")
NDROI.template-   field(SCAN, "I/O Intr")
NDROI.template-}
NDROI.template-
--
NDROI.template-   field(PINI, "YES")
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(OUT,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))COLLAPSE_DIMS")
NDROI.template-   field(VAL,  "0")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   info(autosaveFields, "VAL")
NDROI.template-}
NDROI.template-
NDROI.template-record(bi, "$(P)$(R)CollapseDims_RBV")
NDROI.template-{
NDROI.template-   field(DTYP, "asynInt32")
NDROI.template-   field(INP,  "@asyn($(PORT),$(ADDR=0),$(TIMEOUT=1))COLLAPSE_DIMS")
NDROI.template-   field(ZNAM, "Disable")
NDROI.template:   field(ONAM, "Enable")
NDROI.template-   field(ZSV,  "NO_ALARM")
NDROI.template-   field(OSV,  "MINOR")
NDROI.template-   field(SCAN, "I/O Intr")
NDROI.template-}
```

**Comment by bhill-slac** [comment]
Good point.   I've gone through the other ONAM/ZNAM and added some more Enable to Enabled and Disable to Disabled changes to this pull request.

**Comment by MarkRivers** [comment]
I just did a search of the SPEC macros in use at the APS for the string "Enable".  I found these for example:
```
./macros_aps/common/bcda/AreaDetector.mac:      epics_put(sprintf("%sEnableCallbacks",ADROIPV),"Enable")
./macros_aps/common/bcda/AreaDetector.mac:      #Enable statistics asyn port
./macros_aps/common/bcda/AreaDetector.mac:      epics_put(sprintf("%sEnableCallbacks",ADROIPV),"Enable")
./macros_aps/common/bcda/AreaDetector.mac:      epics_put(sprintf("%sEnableCallbacks",ADSTATPV),"Enable")
./macros_aps/common/bcda/AreaDetector.mac:    epics_put(sprintf("%sEnableCallbacks","$1"),"Enable")
```
This pull request would thus potentially break SPEC at all beamlines that use it at the APS.  It would be necessary to first determine which version of ADCore was in use and change the string to Enable or Enabled depending on the version.  Alternatively one could change it to use the numeric values, but that makes it less clear.

I suspect there are many other sites that have written clients that use the names (Enable/Disable) rather than the values (1/0) when writing or reading these PVs.

I thus believe this change introduces unneeded complexity, and the lack of backwards compatibility is not worth the gain in clarity.

**Pull request closed without merging**
