### PR TITLE
fix bitshuffle filter for NDArray codec property

### PR DESCRIPTION
**Pull request by xiaoqiangwang**
After the recent introduction of Codec into NDArray, this filter does not compress anymore. This fix adapts to use the Codec property.

### CODE REVIEW

**Comment by xiaoqiangwang** [comment]
The test on windows-x64 host arch shows it is functional. But on linux-x86_64, the write of bitshuffle filter results in crash.
```
#0  0x00007ffff5ab20cf in _int_free () from /lib64/libc.so.6
#1  0x00007fffcb0cded8 in bshuf_h5_filter (flags=<optimized out>, cd_nelmts=5, cd_values=0x7fffd4094b20, nbytes=<optimized out>, buf_size=0x7ffff4f96c20,
    buf=0x7ffff4f96c00) at ../../supportApp/hdf5Src/bshuf_h5filter.c:193
#2  0x00007fffcb09ec09 in H5Z_pipeline (pline=0x7fffd4091b68, flags=flags@entry=0, filter_mask=filter_mask@entry=0x7ffff4f96c90, edc_read=<optimized out>,
    cb_struct=..., nbytes=nbytes@entry=0x7ffff4f96c30, buf_size=buf_size@entry=0x7ffff4f96c20, buf=buf@entry=0x7ffff4f96c00)
    at ../../supportApp/hdf5Src/H5Z.c:1419
#3  0x00007fffcadc699b in H5D__chunk_flush_entry (dset=0x7fffd4091a10, dxpl_id=720575940379279396, dxpl_cache=0x7fffcb3d2260 <H5D_def_dxpl_cache>,
    ent=0x7ffff4f96f20, reset=<optimized out>) at ../../supportApp/hdf5Src/H5Dchunk.c:2862
#4  0x00007fffcadcca7e in H5D__chunk_unlock (naccessed=1048576, chunk=0x7fffd4195250, dirty=true, udata=0x7ffff4f96d80, io_info=0x7ffff4f97230)
    at ../../supportApp/hdf5Src/H5Dchunk.c:3631
#5  H5D__chunk_write (io_info=0x7ffff4f97230, type_info=0x7ffff4f971b0, nelmts=<optimized out>, file_space=<optimized out>, mem_space=<optimized out>,
    fm=0x7fffd40eba80) at ../../supportApp/hdf5Src/H5Dchunk.c:2234
#6  0x00007fffcadf5170 in H5D__write (dataset=dataset@entry=0x7fffd4091a10, mem_type_id=mem_type_id@entry=216172782113784121, mem_space=<optimized out>,
    mem_space@entry=0x7fffd408aed0, file_space=file_space@entry=0x7fffd40d9010, dxpl_id=dxpl_id@entry=720575940379279368, buf=<optimized out>,
    buf@entry=0x7fffcc201330) at ../../supportApp/hdf5Src/H5Dio.c:790
#7  0x00007fffcadf57d4 in H5D__pre_write (dset=dset@entry=0x7fffd4091a10, direct_write=<optimized out>, mem_type_id=mem_type_id@entry=216172782113784121,
    mem_space=0x7fffd408aed0, file_space=0x7fffd40d9010, dxpl_id=dxpl_id@entry=720575940379279368, buf=buf@entry=0x7fffcc201330)
    at ../../supportApp/hdf5Src/H5Dio.c:344
#8  0x00007fffcadf5b67 in H5Dwrite (dset_id=<optimized out>, mem_type_id=216172782113784121, mem_space_id=288230376151711746,
    file_space_id=288230376151711796, dxpl_id=720575940379279368, buf=0x7fffcc201330) at ../../supportApp/hdf5Src/H5Dio.c:268
#9  0x00007fffca8c93ea in NDFileHDF5Dataset::writeFile(NDArray*, long, long, unsigned long long*) ()
   from /ioc/modules/NDPluginHDF5/pre3.5/R7.0.1/lib/RHEL7-x86_64/libNDPluginHDF5.so
#10 0x00007fffca8c39dc in NDFileHDF5::writeFile(NDArray*) () from /ioc/modules/NDPluginHDF5/pre3.5/R7.0.1/lib/RHEL7-x86_64/libNDPluginHDF5.so
```

**Comment by MarkRivers** [comment]
It appears to me that there is a bug in bshuf_h5filter.c:193.  It is calling free() without testing to see if it is NULL pointer.  It seems to me that it is set to be a NULL pointer on line 2804 of H5Dchunk.c

**Comment by xiaoqiangwang** [comment]
I tried to print the address of `*buf` and it is not NULL. When comparing `blosc_filter.c` and` bshuf_h5filter.c`, they both free the input `buf`, but blosc_h5filter calls `H5free_memory` instead `free`. y making the same change to `bshuf_h5filter.c` the crash does not go away.

I wonder whether this crash can be reproduced on your Linux systems at all.

**Comment by xiaoqiangwang** [comment]
I created https://github.com/areaDetector/ADSupport/pull/27 to avoid this crash on Linux. It continues to work on Windows.

**Comment by GDYendell** [comment]
As far as I can tell, this will specifically make `NDCODEC_BSLZ4` work under lazy open. It should have already worked if the compression was set correctly on the `NDFileHDF5`, but now it doesn't need to be as it will be overridden by the codec on the `NDArray`.

**Pull request merged**
