### PR TITLE
Compile tests for WIN32

### PR DESCRIPTION
**Pull request by stuwilkins**
Hi, 
I tried to get the unit tests to compile with BOOST on WIN32 hosts. I have been trying this with the lastest MSVC on Windows 10. I get a strange link time error which I can't get though. If I don't compile with the `test_NDFileHDF5ExtraDimensions.cpp` the it all compiles and links ok and the tests run OK. 

I am seeing if someone can spot the errors who is better than me at windows.

This is part of an idea I have to build AD on windows and linux using azure pipelines. 

Any help appreciated!

### CODE REVIEW

**Comment by MarkRivers** [comment]
I am a bit confused.  You said the test is failing on Windows.  But the Travis failure above is actually on linux-x86_64, where it says that shared_ptr is not a member of std.

```
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE            -D_X86_64_  -DUNIX  -Dlinux     -g   -Wall     --coverage -DH5_NO_DEPRECATED_SYMBOLS -DH5Dopen_vers=2 -DH5Gcreate_vers=2  -mtune=generic     -m64  -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include -I/home/travis/build/areaDetector/ADCore/external/epics_base//include/compiler/gcc -I/home/travis/build/areaDetector/ADCore/external/epics_base//include/os/Linux -I/home/travis/build/areaDetector/ADCore/external/epics_base//include   -I/home/travis/build/areaDetector/ADCore/external/asyn-R4-32/include  -I/home/travis/build/areaDetector/ADCore/external/ADSupport/include/os/Linux -I/home/travis/build/areaDetector/ADCore/external/ADSupport/include        -c ../test_NDFileHDF5AttributeDataset.cpp
../test_NDFileHDF5AttributeDataset.cpp: In member function ‘void test_AttributeOriginalDataset::test_method()’:
../test_NDFileHDF5AttributeDataset.cpp:41:3: error: ‘shared_ptr’ is not a member of ‘std’
   std::shared_ptr<NDFileHDF5AttributeDataset> adPtr;
```

Can you include the link error you are getting on Windows?

**Comment by MarkRivers** [comment]
I see you changed from std::tr1:;shared_ptr to std::shared_ptr.  The latter is only supported in C++11.  Is it possible that the Travis compiler on linux-x86_64 is not C++11 by default?

**Comment by stuwilkins** [comment]
Hi @MarkRivers yes travis is not C++11 by default, I am trying with that fixed

**Comment by stuwilkins** [comment]
Closing and moving to #381

**Pull request closed without merging**
